language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed juliejin/udagram-api-feed:v1
  - docker tag reverseproxy juliejin/reverseproxy:v1
  - docker tag udagram-api-user juliejin/udagram-api-user:v1
  - docker tag udagram-frontend juliejin/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push juliejin/udagram-api-feed:v1
  - docker push juliejin/udagram-frontend:v2
  - docker push juliejin/reverseproxy:v2
  - docker push juliejin/udagram-api-user:v1
