apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    app: backend-user
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: backend-user